export default {
  data: {
    birds: [
      {
        species: 'American Bittern',
        fileExt: 'americanBittern',
        category: 'Bittern, Heron, Ibis',
        status: 'infrequent',
        frequency: 'less common',
      },
      {
        species: 'Green Heron',
        fileExt: 'greenHeron',
        category: 'Bittern, Heron, Ibis',
        status: 'annual migrant',
        frequency: 'less common',
      },
      {
        species: 'Great Blue Heron',
        fileExt: 'greatBlueHeron',
        category: 'Bittern, Heron, Ibis',
        status: 'year-round',
        frequency: 'common',
      },
      {
        species: 'Great Egret',
        fileExt: 'greatEgret',
        category: 'Bittern, Heron, Ibis',
        status: 'annual migrant',
        frequency: 'common',
      },
      {
        species: 'Snowy Egret',
        fileExt: 'snowyEgret',
        category: 'Bittern, Heron, Ibis',
        status: 'annual migrant',
        frequency: 'less common',
      },
      {
        species: 'Black-crowned Night Heron',
        fileExt: 'blackCrownedNightHeron',
        category: 'Bittern, Heron, Ibis',
        status: 'annual migrant',
        frequency: 'common',
      },
      {
        species: 'Snow Goose',
        fileExt: 'snowGoose',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'less common',
      },
      {
        species: 'Gadwall',
        fileExt: 'gadwall',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'less common',
      },
      {
        species: 'Green-winged Teal',
        fileExt: 'greenWingedTeal',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'less common',
      },
      {
        species: 'Canvasback',
        fileExt: 'canvasback',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'less common',
      },
      {
        species: 'Ring-necked Duck',
        fileExt: 'ringNeckedDuck',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'less common',
      },
      {
        species: 'Lesser Scaup',
        fileExt: 'lesserScaup',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'less common',
      },
      {
        species: 'Hooded Merganser',
        fileExt: 'hoodedMerganser',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'less common',
      },
      {
        species: 'Canada Goose',
        fileExt: 'canadaGoose',
        category: 'Waterfowl',
        status: 'year-round',
        frequency: 'common',
      },
      {
        species: 'Mallard',
        fileExt: 'mallard',
        category: 'Waterfowl',
        status: 'year-round',
        frequency: 'common',
      },
      {
        species: 'American Black Duck',
        fileExt: 'americanBlackDuck',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'common',
      },
      {
        species: 'Northern Shoveler',
        fileExt: 'northernShoveler',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'common',
      },
      {
        species: 'Bufflehead',
        fileExt: 'bufflehead',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'common',
      },
      {
        species: 'Ruddy Duck',
        fileExt: 'ruddyDuck',
        category: 'Waterfowl',
        status: 'annual migrant',
        frequency: 'common',
      },
    ],
  },
};
