const birdData = {
  birds: [
    {
      species: 'Ruddy Duck',
      fileExt: 'ruddyDuck',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'common',
      id: 0,
      count: 0,
    },
    {
      species: 'American Bittern',
      fileExt: 'americanBittern',
      category: 'Bittern, Heron, Ibis',
      status: 'infrequent',
      frequency: 'less common',
      id: 1,
      count: 0,
    },
    {
      species: 'Green Heron',
      fileExt: 'greenHeron',
      category: 'Bittern, Heron, Ibis',
      status: 'annual migrant',
      frequency: 'less common',
      id: 2,
      count: 0,
    },
    {
      species: 'Great Blue Heron',
      fileExt: 'greatBlueHeron',
      category: 'Bittern, Heron, Ibis',
      status: 'year-round',
      frequency: 'common',
      id: 3,
      count: 0,
    },
    {
      species: 'Great Egret',
      fileExt: 'greatEgret',
      category: 'Bittern, Heron, Ibis',
      status: 'annual migrant',
      frequency: 'common',
      id: 4,
      count: 0,
    },
    {
      species: 'Snowy Egret',
      fileExt: 'snowyEgret',
      category: 'Bittern, Heron, Ibis',
      status: 'annual migrant',
      frequency: 'less common',
      id: 5,
      count: 0,
    },
    {
      species: 'Black-crowned Night Heron',
      fileExt: 'blackCrownedNightHeron',
      category: 'Bittern, Heron, Ibis',
      status: 'annual migrant',
      frequency: 'common',
      id: 6,
      count: 0,
    },
    {
      species: 'Snow Goose',
      fileExt: 'snowGoose',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'less common',
      id: 7,
      count: 0,
    },
    {
      species: 'Gadwall',
      fileExt: 'gadwall',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'less common',
      id: 8,
      count: 0,
    },
    {
      species: 'Green-winged Teal',
      fileExt: 'greenWingedTeal',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'less common',
      id: 9,
      count: 0,
    },
    {
      species: 'Canvasback',
      fileExt: 'canvasback',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'less common',
      id: 10,
      count: 0,
    },
    {
      species: 'Ring-necked Duck',
      fileExt: 'ringNeckedDuck',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'less common',
      id: 11,
      count: 0,
    },
    {
      species: 'Lesser Scaup',
      fileExt: 'lesserScaup',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'less common',
      id: 12,
      count: 0,
    },
    {
      species: 'Hooded Merganser',
      fileExt: 'hoodedMerganser',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'less common',
      id: 13,
      count: 0,
    },
    {
      species: 'Canada Goose',
      fileExt: 'canadaGoose',
      category: 'Waterfowl',
      status: 'year-round',
      frequency: 'common',
      id: 14,
      count: 0,
    },
    {
      species: 'Mallard',
      fileExt: 'mallard',
      category: 'Waterfowl',
      status: 'year-round',
      frequency: 'common',
      id: 15,
      count: 0,
    },
    {
      species: 'American Black Duck',
      fileExt: 'americanBlackDuck',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'common',
      id: 16,
      count: 0,
    },
    {
      species: 'Northern Shoveler',
      fileExt: 'northernShoveler',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'common',
      id: 17,
      count: 0,
    },
    {
      species: 'Bufflehead',
      fileExt: 'bufflehead',
      category: 'Waterfowl',
      status: 'annual migrant',
      frequency: 'common',
      id: 18,
      count: 0,
    },
  ],
};

export default birdData;
